### ISSUE TITLE
Bridge setGain

### ISSUE THREAD

**Issue by whodeee** [evantahler/nodePhidgets#25]
The setGain method is not working properly.  It is changing the gain value but the output coming from the board is not being affected.  The min and max values are also not be adjusted accordingly.

**Comment by cotejp** [comment]
You are right. There was a confusion between the actual gain values (1, 8, 16, 32, 64, 128) and the values that must be sent to the WebService's API (1, 2, 3, 4, 5, 6). This has been fixed with [PR26](https://github.com/evantahler/nodePhidgets/pull/26).

Please download [version 0.5.8 from NPM](https://www.npmjs.com/package/phidgets) and let me know if it works for you.

P.S. Sorry for the delay and thanks for reporting the problem!

**Comment by whodeee** [comment]
Great, so is the documentation correct that the values should be set to 1,8,16,32,64,128?

**Comment by cotejp** [comment]
Yep. The documentation is correct.

**Comment by cotejp** [comment]
Since it seems to be working for you, I'll close this. If it does not, please re-open.
